### ISSUE TITLE
Plz. Update this Version to the newest one. 

### ISSUE THREAD

**Issue by CloudWolf99** [jakowenko/double-take-hassio-addons#12]
There some issues in this version from deepstack. Plz update to current version.

**Comment by niemyjski** [comment]
+1

**Comment by jakowenko** [comment]
What is the issue? When you install it I believe it should be pulling the latest DeepStack version. Happy to bump something specific though if you can tell me what.

https://github.com/twentyfourg/2772-1-lxp-base-api/pull/102/files

**Comment by niemyjski** [comment]
I'm still on 1.7.0, I think you need to update a meta file for every release?

**Comment by niemyjski** [comment]
@jakowenko I think you need to update this: https://github.com/jakowenko/double-take-hassio-addons/blob/master/stable/config.json#L3 I'm just going off what they did here: https://github.com/hassio-addons/repository/commit/29acbc4ed62677a7f53a5bcaac2edcadb5a3eb4f

**Comment by jakowenko** [comment]
Oh sorry, I thought the original issue was about the DeepStack version. I just bumped the Double Take add-on version to 1.9.0.

![2022-05-23 at 14 29 38](https://user-images.githubusercontent.com/1081811/169884578-55c05837-9d29-4db4-952f-df8c872dd41e.png)

Feel free to open a new issue if there are any problems with the new version.
