### ISSUE TITLE
RAM usage

### ISSUE THREAD

**Issue by fer112233** [jakowenko/double-take-hassio-addons#13]
Hi, I'm using double take with compreface in my Home Assistant installation, however compreface is using almost 4GB of RAM on it's own, which seems a bit weird to me. Is that too much? Should I give it more RAM?

Thank you!

**Comment by totalitarian** [comment]
Same here, especially as it will be idling most of the time

**Comment by jakowenko** [comment]
I believe this is normal or might be best asked over on the [CompreFace repo](https://github.com/exadel-inc/CompreFace).

I just checked my container that is running on my MBP and it's also using over 4GB of memory between all of the services. All the addon is doing is running single container version of CompreFace.

<img width="628" alt="2022-10-19 at 00 31 40@2x" src="https://user-images.githubusercontent.com/1081811/196598279-60e45ae2-a20e-425e-981f-4644db456c10.png">
