### ISSUE TITLE
Double-Take-Proxy results in 404 error

### ISSUE THREAD

**Issue by mhoogenbosch** [jakowenko/double-take-hassio-addons#26]
Double take proxy was working for a pretty long time. No problems at all. Since recently, it gives a 404 error.

![image](https://github.com/jakowenko/double-take-hassio-addons/assets/36899598/d51ad2a8-a712-418c-9f2e-777f6eb58f3d)

If I manually paste the configured IP address with port number into my browser, double-take starts up just fine, it is just the proxy part which doesn't work.

There are no logs anywhere, at least, non I can find. The log of the addon just shows it is started without an issue. And inside double take the log shows no error, just faces getting recognized.

Is this something commonly?

Running the latest software i'm aware of:

Home Assistant 2023.8.2
Supervisor 2023.08.1
Frontend-versie: 20230802.0 - latest

Double take v1.13.10 on a docker host based on a pi4.

Double-take-proxy is the latest 1.0.0 version.

**Comment by danielholm** [comment]
Same thing for me since yesterday. It was working fine, then I restarted my docker container and now this. In a browser it works just fine. Tried reinstall to no avail.

**Comment by ParksideParade** [comment]
I started getting this error immediately after updating to 1.13.11. Running on Home Assistant OS as a HACS add-on.

If I click on the Config tab of Double Take, I get a password box and this error notification in HA:

_Login attempt or request with invalid authentication from xxx.xxx.com (xx.xx.xx.xx). See the log for details._

**Comment by mhoogenbosch** [comment]
> I started getting this error immediately after updating to 1.13.11. Running on Home Assistant OS as a HACS add-on.
> 
> If I click on the Config tab of Double Take, I get a password box and this error notification in HA:
> 
> _Login attempt or request with invalid authentication from xxx.xxx.com (xx.xx.xx.xx). See the log for details._

Exactly the same thing and version numbers.

Also the password question on config page. Haven't noticed this before.

**Comment by ParksideParade** [comment]
Possibly related... I got this Double Take error yesterday when I connected to my Home Assistant from work. Just a couple minutes later, my usually rock-solid home wifi router went down completely. I had to reboot my router when I got home.

From my Googling, I see a few cases of HA or add-on bugs taking down a network due to mDNS flooding. Possibly related?

I'm happy to debug further if anyone can point me to the appropriate log files / etc.

**Comment by amkrafie** [comment]
I'm also just now getting this issue, I rebuilt my container with new configs and thought that's what did it but it seems like it's not my fault!

**Comment by chjud** [comment]
same problem here

**Comment by mhoogenbosch** [comment]
Works again for me. Addon didn't get updated. 

Double take is on vesion 1.13.11.2
