### ISSUE TITLE
Can i expand your addon? 

### ISSUE THREAD

**Issue by Sangoku** [jakowenko/double-take-hassio-addons#3]
Hello.
Just asking...
I want to add the 2 other detectors to this add-on. Is it OK  for you that I expand it?

**Comment by jakowenko** [comment]
Yes, you're definitely welcome to open a PR with the additional detectors. What were you thinking about adding?

**Comment by Sangoku** [comment]
For now the facebox addon with config options and readme. Then when i figure out how to install the last one that one to. I will add documentation to ^^ this is my new faw  pet project

**Comment by jakowenko** [comment]
Sounds great! Let me know what I can do to help. I'm working on a CompreFace addon.

**Comment by Sangoku** [comment]
Will do :)

**Comment by Sangoku** [comment]
Almost done. Will push tomorow when i test it :3

**Comment by Sangoku** [comment]
Hmmm. 
Kinda got stuck yesterday  on this problem. I added all files etc but when I try to install it the supervisor says 

 ERROR (SyncWorker_1) [supervisor.docker.addon] Invalid build environment, can't build this add-on!

Have to google why it is happening.

**Comment by jakowenko** [comment]
Thanks for contributing!

**Comment by Sangoku** [comment]
Was a pleasure :D
