### ISSUE TITLE
Sensors Not Being Created

### ISSUE THREAD

**Issue by LordNex** [jakowenko/double-take-hassio-addons#7]
My current setup includes a RPi4 running only Frigate, a Jetson Nano running the Jetpack version of DeepStack, and an i5 laptop running Home Assistant and Double Take among the rest of the majority of my integrations and automations. There are 3 people in my house that I've been working to train and setup actionable notifications that allow them to unlock the door if they are detected and their Device is home. The problem is that not all of the sensors seems to have been created. Mine and my wife's sensors created ok, and even though I have an even in frigate and a detection in DT from DS, the sensor hasn't been created. I'm not seeing anything that pops out at me in the HA logs but I might just be overlooking something. Any suggestion or command you have that cam force a creation of the HA sensors for trained faces?

And also, thanks for this kick ass integration. This makes what I was going to do soooooooo much easier! Way to go man! 👍

**Comment by LordNex** [comment]
This is resolved

**Comment by Nydery** [comment]
I have the same problem: none of my 2 trained faces have been created as sensors.
How did you resolve the issue?
